version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - '3306:3306'
    env_file:
      - ./api/.env.development
    volumes:
      - ./api/data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10  

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '3030:3030'
    depends_on:
      db:
        condition: service_healthy

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - api

