version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    env_file:
      - ./api/.env.development
    volumes:
      - ./api/data:/var/lib/mysql

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '3030:3030'
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - api

