version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    container_name: integration-tests-prisma
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=mytestdb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=12345